### ISSUE TITLE
EPIC: Create Abstraction Layer over SATP implementation

### ISSUE THREAD

**Issue by AndreAugusto11** [RafaelAPB/blockchain-integration-framework#49]
**Description**
An important feature for the implementation of SATP is to add an abstraction layer on top of the protocol to allow multiple different executions using gateways, including the integration of other tools or fine-tuning an execution of SATP.

**PART 1: Design the new layer**
1. The codebase is getting larger and larger, so it would be important to first roughly design this component and the expected functionality in a couple of scenarios. Find relevant design patterns that can simplify the implementation. #58 

**PART 2: Implement the skeleton of the new layer**
1. Implement the skeleton of the architecture #59

**PART 3: Fine-tunning an SATP session**
1. It should be possible to inject predefined functions (that enforce a set of rules) in whatever stage of the protocol #60

**PART 4: Add support for the integration of external SDKs through the Gateway**
1. Design and implement an integration API for users to interact with #61
2. Development of connectors for specific SDKs that will be needed in the project (e.g., for Anchorage) #62

**Comment by AndreAugusto11** [comment]
@RafaelAPB pls add labels and assign this to us

**Comment by RafaelAPB** [comment]
Thanks for working on this @AndreAugusto11
