### ISSUE TITLE
Design SATP abstraction layer

### ISSUE THREAD

**Issue by AndreAugusto11** [RafaelAPB/blockchain-integration-framework#58]
Create a simple architecture image for the rule orchestrator. This will allow us to be on the same page concerning the functionality of this new layer and add value to the architecture document.

Tasks:
1. Create a high-level design document outlining the architecture of the abstraction layer.
2. Explore relevant design patterns suitable for simplifying the implementation

**Comment by RafaelAPB** [comment]
I believe we can close this: 
![SATP-Hermes Architecture draft v0 1 - Page 1 (1)](https://github.com/RafaelAPB/blockchain-integration-framework/assets/11261236/e81cfed0-b5c1-4461-81ad-cdcda0a5ab6f)
