### ISSUE TITLE
Fine-Tuning SATP Session with Predefined Functions

### ISSUE THREAD

**Issue by AndreAugusto11** [RafaelAPB/blockchain-integration-framework#60]
Allow for user input at various stages of the SATP protocol.

Tasks:
1. Define a mechanism to allow for user input during different stages of SATP execution.
3. Test using functions that implement some kind of business rules in the middle of the execution of the protocol

depends on #61

**Comment by RafaelAPB** [comment]
Should take as input a configuration file, possibly the one that each Cacti receives

**Comment by RafaelAPB** [comment]
https://github.com/hyperledger/cacti/issues/3179
